<?php

/**
 * This is the model base class for the table "p8_size".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Size".
 *
 * Columns in table "p8_size" available as properties of the model,
 * followed by relations of table "p8_size" available as properties of the model.
 *
 * @property string $id
 * @property string $size
 *
 * @property Product[] $p8Products
 */
abstract class BaseSize extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'p8_size';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Size|Sizes', $n);
	}

	public static function representingColumn() {
		return 'size';
	}

	public function rules() {
		return array(
			array('size', 'length', 'max'=>255),
			array('size', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, size', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'p8Products' => array(self::MANY_MANY, 'Product', 'p8_size_product(size_id, product_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'p8Products' => 'SizeProduct',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'size' => Yii::t('app', 'Size'),
			'p8Products' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('size', $this->size, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}