<?php

/**
 * This is the model base class for the table "p8_product".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Product".
 *
 * Columns in table "p8_product" available as properties of the model,
 * followed by relations of table "p8_product" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $price
 * @property string $date_inserted
 * @property string $description
 * @property string $category_id
 *
 * @property Image[] $images
 * @property Category $category
 * @property Tag[] $p8Tags
 */
abstract class BaseProduct extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'p8_product';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Product|Products', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, price, category_id', 'required'),
			array('name', 'length', 'max'=>255),
			array('price', 'length', 'max'=>6),
			array('category_id', 'length', 'max'=>10),
			array('date_inserted, description', 'safe'),
			array('date_inserted, description', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, price, date_inserted, description, category_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'images' => array(self::HAS_MANY, 'Image', 'product_id'),
			'category' => array(self::BELONGS_TO, 'Category', 'category_id'),
			'p8Tags' => array(self::MANY_MANY, 'Tag', 'p8_tag_product(product_id, tag_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'p8Tags' => 'TagProduct',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'price' => Yii::t('app', 'Price'),
			'date_inserted' => Yii::t('app', 'Date Inserted'),
			'description' => Yii::t('app', 'Description'),
			'category_id' => null,
			'images' => null,
			'category' => null,
			'p8Tags' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('price', $this->price, true);
		$criteria->compare('date_inserted', $this->date_inserted, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('category_id', $this->category_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}