<?php

/**
 * This is the model base class for the table "p8_product_fabric".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProductFabric".
 *
 * Columns in table "p8_product_fabric" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $product_id
 * @property string $fabric_id
 * @property string $price
 *
 */
abstract class BaseProductFabric extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'p8_product_fabric';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProductFabric|ProductFabrics', $n);
	}

	public static function representingColumn() {
		return array(
			'product_id',
			'fabric_id',
		);
	}

	public function rules() {
		return array(
			array('product_id, fabric_id, price', 'required'),
			array('product_id, fabric_id', 'length', 'max'=>10),
			array('price', 'length', 'max'=>6),
			array('product_id, fabric_id, price', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'product_id' => null,
			'fabric_id' => null,
			'price' => Yii::t('app', 'Price'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('product_id', $this->product_id);
		$criteria->compare('fabric_id', $this->fabric_id);
		$criteria->compare('price', $this->price, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}