<?php

/**
 * This is the model base class for the table "p8_option".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Option".
 *
 * Columns in table "p8_option" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $name
 * @property integer $enabled
 * @property string $optionalData
 *
 */
abstract class BaseOption extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'p8_option';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Option|Options', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('enabled', 'numerical', 'integerOnly'=>true),
			array('name', 'length', 'max'=>255),
			array('optionalData', 'safe'),
			array('enabled, optionalData', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, enabled, optionalData', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'enabled' => Yii::t('app', 'Enabled'),
			'optionalData' => Yii::t('app', 'Optional Data'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('enabled', $this->enabled);
		$criteria->compare('optionalData', $this->optionalData, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}