<?php

/**
 * This is the model base class for the table "p8_measurement".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Measurement".
 *
 * Columns in table "p8_measurement" available as properties of the model,
 * followed by relations of table "p8_measurement" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $description
 *
 * @property Product[] $p8Products
 */
abstract class BaseMeasurement extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'p8_measurement';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Measurement|Measurements', $n);
	}

	public static function representingColumn() {
		return 'description';
	}

	public function rules() {
		return array(
			array('description', 'required'),
			array('name', 'length', 'max'=>255),
			array('name', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, name, description', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'p8Products' => array(self::MANY_MANY, 'Product', 'p8_product_measurement(measurement_id, product_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'p8Products' => 'ProductMeasurement',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'p8Products' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}