<?php

/**
 * This is the model base class for the table "p8_image".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Image".
 *
 * Columns in table "p8_image" available as properties of the model,
 * followed by relations of table "p8_image" available as properties of the model.
 *
 * @property string $id
 * @property string $product_id
 * @property string $url
 *
 * @property Product $product
 * @property Product[] $products
 */
abstract class BaseImage extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'p8_image';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Image|Images', $n);
	}

	public static function representingColumn() {
		return 'url';
	}

	public function rules() {
		return array(
			array('product_id', 'required'),
			array('product_id', 'length', 'max'=>10),
			array('url', 'length', 'max'=>255),
			array('url', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, product_id, url', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'product' => array(self::BELONGS_TO, 'Product', 'product_id'),
			'products' => array(self::HAS_MANY, 'Product', 'default_image_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'product_id' => null,
			'url' => Yii::t('app', 'Url'),
			'product' => null,
			'products' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('product_id', $this->product_id);
		$criteria->compare('url', $this->url, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}