<?php

/**
 * This is the model base class for the table "p8_gallery".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Gallery".
 *
 * Columns in table "p8_gallery" available as properties of the model,
 * followed by relations of table "p8_gallery" available as properties of the model.
 *
 * @property string $id
 * @property string $url
 * @property string $alt_description
 * @property string $product_id
 *
 * @property Product $product
 */
abstract class BaseGallery extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'p8_gallery';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Gallery|Galleries', $n);
	}

	public static function representingColumn() {
		return 'url';
	}

	public function rules() {
		return array(
			array('alt_description', 'required'),
			array('url, alt_description', 'length', 'max'=>255),
			array('product_id', 'length', 'max'=>10),
			array('url, product_id', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, url, alt_description, product_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'product' => array(self::BELONGS_TO, 'Product', 'product_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'url' => Yii::t('app', 'Url'),
			'alt_description' => Yii::t('app', 'Alt Description'),
			'product_id' => null,
			'product' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('alt_description', $this->alt_description, true);
		$criteria->compare('product_id', $this->product_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}