<?php

/**
 * This is the model base class for the table "p8_newsletter".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Newsletter".
 *
 * Columns in table "p8_newsletter" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $email
 * @property string $date_enrolled
 *
 */
abstract class BaseNewsletter extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'p8_newsletter';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Newsletter|Newsletters', $n);
	}

	public static function representingColumn() {
		return 'email';
	}

	public function rules() {
		return array(
			array('email', 'length', 'max'=>255),
			array('date_enrolled', 'safe'),
			array('email, date_enrolled', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, email, date_enrolled', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'email' => Yii::t('app', 'Email'),
			'date_enrolled' => Yii::t('app', 'Date Enrolled'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('date_enrolled', $this->date_enrolled, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}