<?php

/**
 * This is the model base class for the table "p8_category".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Category".
 *
 * Columns in table "p8_category" available as properties of the model,
 * followed by relations of table "p8_category" available as properties of the model.
 *
 * @property string $id
 * @property string $name
 * @property string $description
 * @property string $keywords
 *
 * @property Product[] $products
 */
abstract class BaseCategory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'p8_category';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Category|Categories', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, description, keywords', 'required'),
			array('name, keywords', 'length', 'max'=>255),
			array('id, name, description, keywords', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'products' => array(self::HAS_MANY, 'Product', 'category_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'keywords' => Yii::t('app', 'Keywords'),
			'products' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('keywords', $this->keywords, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}