<?php

/**
 * This is the model base class for the table "p8_product_measurement".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "ProductMeasurement".
 *
 * Columns in table "p8_product_measurement" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $product_id
 * @property string $measurement_id
 *
 */
abstract class BaseProductMeasurement extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'p8_product_measurement';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'ProductMeasurement|ProductMeasurements', $n);
	}

	public static function representingColumn() {
		return array(
			'product_id',
			'measurement_id',
		);
	}

	public function rules() {
		return array(
			array('product_id, measurement_id', 'required'),
			array('product_id, measurement_id', 'length', 'max'=>10),
			array('product_id, measurement_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'product_id' => null,
			'measurement_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('product_id', $this->product_id);
		$criteria->compare('measurement_id', $this->measurement_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}